
INSERT INTO page_blocks (page_slug, block_type, block_order, content, is_visible) VALUES
('home', 'hero', 0, '{"label":"AMUMA","heading":"A New Way of Traveling","body":"Tourism is changing. Travelers are moving away from crowded destinations and standardized resorts. They are searching for something more rare. Not bigger places — but more meaningful ones. Hidden coastlines. Untouched islands. Villages where hospitality still feels personal. Places where beauty is not manufactured, but discovered.\n\nAMUMA was created to reveal these hidden treasures — a network of intimate retreats designed for explorers who seek beauty, silence, and discovery.","cta":"Join the Founding Circle","cta_target":"#join"}', true),
('home', 'text', 1, '{"heading":"The AMUMA Circle","body":"AMUMA is not simply a collection of hotels. It is a circle of travelers who share a way of exploring the world. Members return to the retreats not only as guests but as part of a living community. They discover new places together, host friends and family, and move across destinations connected by the same spirit of hospitality.\n\nEach retreat becomes both a sanctuary in nature and a meeting point for the community."}', true),
('home', 'text', 2, '{"heading":"Hidden Destinations","body":"AMUMA retreats are created only in places that still feel undiscovered. Not where tourism already dominates. But where nature, culture, and simplicity still define the landscape.\n\nThese are destinations where a small retreat can coexist with the environment while preserving the beauty that makes the place special."}', true),
('home', 'text', 3, '{"heading":"The AMUMA Experience","body":"Experiences include:"}', true),
('home', 'list', 4, '{"items":["Island exploration","Culinary journeys","Boat adventures","Wellness rituals"],"footnote":"Every moment is designed to feel personal and unhurried."}', true),
('home', 'text', 5, '{"heading":"Pebbles","subheading":"Annual experience credits.","body":"Pebbles are annual experience credits. They can be used for:"}', true),
('home', 'list', 6, '{"items":["Accommodation","Dining","Excursions","Boat trips","Spa treatments"],"footnote":"Pebbles renew every year."}', true),
('home', 'divider', 7, '{}', true),
('home', 'text', 8, '{"heading":"Membership Stakes","subheading":"Ownership and lifestyle.","body":"Members participate in the creation of each retreat through Membership Stakes. Members therefore become both:"}', true),
('home', 'list', 9, '{"items":["Participants in the lifestyle","Partners in the economic success of the retreats"]}', true),
('home', 'divider', 10, '{}', true),
('home', 'text', 11, '{"heading":"Investment Tiers","subheading":"Choose your level of participation."}', true),
('home', 'table', 12, '{"table":{"headers":["Tier","Investment","Shares","Pebbles"],"rows":[["Nova","₱500,000","50","1,000"],["Aurora","₱1,200,000","120","2,200"],["Orion","₱2,000,000","210","4,000"],["Polaris","₱4,000,000","440","8,000"]],"footnote":"The first 20 Nova investors become the Founding Circle."}}', true),
('home', 'divider', 13, '{}', true),
('home', 'text', 14, '{"heading":"Accommodation Usage","subheading":"Pebbles per night."}', true),
('home', 'table', 15, '{"heading":"Suites","table":{"headers":["Season","Pebbles per Night"],"rows":[["Low Season","150"],["High Season","250"],["Peak Season","300"]]}}', true),
('home', 'table', 16, '{"heading":"Villas","table":{"headers":["Season","Pebbles per Night"],"rows":[["Low Season","275"],["High Season","420"],["Peak Season","500"]]}}', true),
('home', 'divider', 17, '{}', true),
('home', 'text', 18, '{"heading":"Revenue Model","subheading":"How income is distributed.","body":"Accommodation revenue enters a shared rental pool."}', true),
('home', 'list', 19, '{"heading":"Distribution","items":["60% → Membership Shareholders","40% → AMUMA Operator"]}', true),
('home', 'list', 20, '{"heading":"Additional Revenues (AMUMA)","items":["Restaurant","Spa","Excursions","Curated experiences"]}', true),
('home', 'divider', 21, '{}', true),
('home', 'text', 22, '{"heading":"Projected Returns","subheading":"Conservative assumptions."}', true),
('home', 'list', 23, '{"items":["Occupancy: 55%","Positioning: Boutique luxury","Tourism tax: TIEZA 5%"]}', true),
('home', 'stats', 24, '{"stats":[{"label":"Projected Annual ROI","value":"17–20%"}]}', true),
('home', 'divider', 25, '{}', true),
('home', 'columns', 26, '{"heading":"Future Destinations","subheading":"A growing constellation of retreats.","columns":[{"heading":"Philippines","items":["Sagada","Siquijor","Sibuyan Island","Bukidnon","Batanes"]},{"heading":"Southeast Asia","items":["Laos","Indonesia","Timor"]}]}', true),
('home', 'divider', 27, '{}', true),
('home', 'text', 28, '{"heading":"The AMUMA Flywheel","body":"Members join\n→\nRetreats are built\n→\nExperiences generate revenue\n→\nReturns fund expansion\n→\nNew destinations appear","subheading":"This cycle continuously expands the AMUMA ecosystem."}', true),
('home', 'divider', 29, '{}', true),
('home', 'text', 30, '{"heading":"First Chapter: Palawan","body":"The journey begins in Palawan, one of the most extraordinary natural environments in the world. The first retreat will rise along the pristine coastline of San Vicente – Long Beach. The second retreat will follow in Balabac, where AMUMA already owns beachfront land.\n\nPalawan will establish the foundation of the AMUMA ecosystem."}', true),
('home', 'text', 31, '{"heading":"The Retreat","subheading":"San Vicente, Palawan","body":"The San Vicente retreat is intentionally small. This scale ensures space, quiet, and genuine connection with nature."}', true),
('home', 'list', 32, '{"label":"Accommodation Units","items":["4 Suites","2 Villas"]}', true),
('home', 'divider', 33, '{}', true),
('home', 'table', 34, '{"heading":"Share Allocation","table":{"headers":["Category","Shares"],"rows":[["Suite (×4)","600 each → 2,400"],["Villa (×2)","1,000 each → 2,000"],["Total","4,400"],["AMUMA Holding","1,600"],["Members","2,800"]]}}', true),
('home', 'divider', 35, '{}', true),
('home', 'timeline', 36, '{"heading":"Roadmap","entries":[{"year":"2026","title":"San Vicente Retreat","detail":"Founding Circle closes, construction begins"},{"year":"2027","title":"Retreat Operational","detail":"First guests welcomed, rental income begins"},{"year":"2028","title":"Second Retreat","detail":"Next destination selected, new share offering"},{"year":"2029+","title":"Network Expansion","detail":"Philippines and Southeast Asia destinations"}]}', true),
('home', 'divider', 37, '{}', true),
('home', 'text', 38, '{"heading":"Team"}', true),
('home', 'text', 39, '{"heading":"James San Vicente","subheading":"Founder · Built Baia","body":"\"Dream high, fly low.\""}', true),
('home', 'stats', 40, '{"stats":[{"value":"9+","label":"Booking scores"},{"value":"4","label":"Keys built"},{"value":"9","label":"Seasons"}]}', true),
('home', 'divider', 41, '{}', true),
('home', 'calculator', 42, '{}', true),
('home', 'divider', 43, '{}', true),
('home', 'columns', 44, '{"heading":"The Member Portal","subheading":"Your Pebbles. Your access. Your ecosystem.","body":"The AMUMA webapp is more than an investment dashboard. It''s the central hub for the entire member experience — where Pebbles become currency, connection, and community.","columns":[{"heading":"Booking & Lifestyle","items":["Reserve stays using Pebbles","Book experiences (island hopping, private cars, transfers, scooter rentals)","Order food and drinks within resorts using Pebbles","Book internal services (massages, spa treatments, private dinners)"]},{"heading":"Finance & Community","items":["Monitor Pebble balance in real-time","Track expected yearly profits","Send or receive Pebbles as gifts to friends/family","Direct messaging channel with resort staff","Event invitations and club member updates","New development progress tracking","Internal voting system for key decisions"]}],"footnote":"Keeping investors in the loop. Always."}', true),
('home', 'divider', 45, '{}', true),
('home', 'text', 46, '{"heading":"Join the Founding Circle","subheading":"20 exclusive Nova spots at ₱500,000"}', true),
('home', 'list', 47, '{"items":["₱500,000 investment (Nova tier)","50 Membership Stakes","1,000 Annual Pebbles","Early access to future AMUMA retreats"],"footnote":"20 spots remaining"}', true),
('home', 'divider', 48, '{}', true),
('home', 'list', 49, '{"label":"Founding Circle Benefits","items":["Name on founding plaque at San Vicente Retreat","Early access to future AMUMA retreats","First access to future share offerings","Annual private video update from James","Invitation to annual Founders'' Dinner","Listed as Founding Circle member on website"]}', true),
('home', 'divider', 50, '{}', true),
('home', 'form', 51, '{}', true),
('home', 'divider', 52, '{}', true),
('home', 'faq', 53, '{"heading":"FAQ","faqs":[{"q":"What are Membership Stakes?","a":"Membership Stakes represent your participation in the creation and economic success of an AMUMA retreat. Members become both participants in the lifestyle and partners in the retreat''s success."},{"q":"What are Pebbles?","a":"Pebbles are annual experience credits. They can be used for accommodation, dining, excursions, boat trips, and spa treatments. They renew every year."},{"q":"Can I sell my stakes?","a":"Yes, stakes are transferable to other verified members within the AMUMA ecosystem."},{"q":"How do I receive my revenue?","a":"Accommodation revenue is distributed from a shared rental pool. 60% goes to Membership Shareholders, 40% to the AMUMA Operator."},{"q":"What''s the minimum investment?","a":"The Nova tier starts at ₱500,000 for 50 shares and 1,000 annual Pebbles."},{"q":"What is the Founding Circle?","a":"The first 20 Nova investors become the Founding Circle and receive early access to future AMUMA retreats."},{"q":"Can companies invest?","a":"Yes. AMUMA welcomes corporate investors, family offices, and entities."},{"q":"What returns can I expect?","a":"Based on conservative assumptions (55% occupancy, boutique luxury positioning), projected annual ROI is 17–20%."}]}', true);
